language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
- ./gradlew check
