language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-29

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-29"

script:
- ./gradlew check
